SELECT a.UniqueID,
       a.Region,
       IFNULL(a.AREA, '') AREA,
       a.Territory,
       a.EnodebSectGrp AS ENODEB_SECT_GRP,
       IFNULL(vpidt.PERSISTENCEPRIORITY, 0) PERSISTENCE_PRIORITY,
       a.Vendor,
       CAST(a.Market AS SIGNED) Market,
       CAST(a.Enodeb AS SIGNED) Enodeb,
       a.EnodebGrp,
       a.BANDGRP,
       a.ENODEBSECTBANDGRPLOGIC,
       a.AGG_UNIQUEID,
       a.DSSEnodebSectCarr,
       a.SiteName,
       a.SiteType,
       a.OprBand,
       IF(a.onairsince > vpidt.generatedon, 'Yes', 'No') AS CarrierIdentifier,
       a.NWFID,
       a.FIPS,
       IFNULL(vpidt.CEC_CURR, '-') CEC_CURR,
       IFNULL(vpidt.BSS_DRIVER_CURR, '-') BSS_DRIVER_CURR,
       IFNULL(vpidt.BSS_PERSEVERANCE5_CURR, 0) BSS_PERSEVERANCE5_CURR,
       IFNULL(vpidt.BSS_PERSEVERANCE12_CURR, 0) BSS_PERSEVERANCE12_CURR,
       IFNULL(vpidt.BSS_CONSECUTIVE_CURR, 0) BSS_CONSECUTIVE_CURR,
       IFNULL(vpidt.CECAF, '0') CECAF,
       a.ENODEBGRPLOGIC,
       a.ENODEBSECTGRPLOGIC,
       a.Seasonal,
       IFNULL(vpidt.SE, 0) SE,
       IFNULL(vpidt.KSP, 0) SectPriority,
       a.MARKETNAME,
       a.technologyType,
       vpidt.MMW_KPI,
       vpidt.LS6_KPI,
  ifnull(vpidt.du,'-') du,    a.AWS, a.AWS3, a.PCS, a.N77, a.CBRS, a.FDMIMO, a.MMW, a.LOAD_TIMESTAMP,    vpidt.LAA_KPI, vpidt.CBRS_KPI, vpidt.CPTMONTH AS CPTMONTH, a.CMANAME,
   IFNULL(vpidt.TAFCURR, 0) TAFCURR,
   IFNULL(vpidt.COMPUTILCURR, 0) COMPUTILCURR,
   IFNULL(vpidt.TRGCURR, '-') TRGCURR,
   IFNULL(vpidt.TRGCURRPCTL, 0) TRGCURRPCTL,
   IFNULL(vpidt.TAFPRJD, 0) TAFPRJD,
   IFNULL(vpidt.TAFPRJDNRM, 0) TAFPRJDNRM,
   IFNULL(vpidt.AVGSECTP100PER, 0) AVGSECTP100PER,
   IFNULL(vpidt.COMPUTILPRJD, 0) COMPUTILPRJD,
   IFNULL(vpidt.TRGPRJD, '-') TRGPRJD,
   IFNULL(vpidt.EXHAUSTDATE, '-') EXHAUSTDATE,
   IFNULL(vpidt.DAYSUSED, 0) DAYSUSED,
   IFNULL(vpidt.FDV_BHUSG3RD, 0) FDVBHUSG3RD,
   IFNULL(vpidt.FDV_PRJD_USG, 0) FDVPRJDUSG,
   IFNULL(vpidt.FDV_PRJD_USG_SCLD, 0) FDVPRJDUSGSCLD,
   IFNULL(vpidt.FDV_CAPACITY, 0) FDVCAPACITY,
   IFNULL(vpidt.FDV_GROWTHRATE, 0) FDVGROWTHRATE,
   IFNULL(vpidt.ASEU_BHUSG3RD, 0) ASEUBHUSG3RD,
   IFNULL(vpidt.ASEU_PRJD_USG, 0) ASEUPRJDUSG,
   IFNULL(vpidt.ASEU_PRJD_USG_SCLD, 0) ASEUPRJDUSGSCLD,
   IFNULL(vpidt.ASEU_CAPACITY, 0) ASEUCAPACITY,
   IFNULL(vpidt.ASEU_GROWTHRATE, 0) ASEUGROWTHRATE,
   IFNULL(vpidt.AVGAC_BHUSG3RD, 0) AVGACBHUSG3RD,
   IFNULL(vpidt.AVGAC_PRJD_USG, 0) AVGACPRJDUSG,
   IFNULL(vpidt.AVGAC_PRJD_USG_SCLD, 0) AVGACPRJDUSGSCLD,
   IFNULL(vpidt.AVGAC_CAPACITY, 0) AVGACCAPACITY,
   IFNULL(vpidt.AVGAC_GROWTHRATE, 0) AVGACGROWTHRATE
 FROM ( SELECT cl.EnodebSectBandGrp UniqueID, MIN(Territory) Territory, MIN(dm.Region) Region, MIN(dm.MarketName) MARKETNAME, cl.Market, MIN(Enodeb) Enodeb, MIN(cl.EnodebSect) EnodebSect, cl.EnodebSectGrp,    GROUP_CONCAT(DISTINCT BANDGRP ORDER BY technologytype SEPARATOR ';') BANDGRP,
   cl.ENODEBSECTBANDGRPLOGIC, cl.AGG_UNIQUEID,
   cl.dss_enodebsectcarr DSSEnodebSectCarr,
   MAX(NWFID) FuzeSiteID,
   MIN(EnodebGrp) EnodebGrp,
   MIN(TechnologyType) technologyType,
   GROUP_CONCAT(DISTINCT SiteName ORDER BY NWFID SEPARATOR ';') SiteName,
   MIN(cl.Vendor) Vendor,
   GROUP_CONCAT(DISTINCT SiteType ORDER BY NWFID SEPARATOR ';') SiteType,
   MAX(cl.NWFID) NWFID,
   MAX(cl.FIPS) FIPS,
   MAX(cl.CMAName) CMANAME,
   MAX(Seasonal) Seasonal,
   GROUP_CONCAT(DISTINCT OprBand ORDER BY technologytype, Carr SEPARATOR ';') OprBand,
   cl.onairsince,
   cl.ENODEBGRPLOGIC,
   cl.ENODEBSECTGRPLOGIC,
   dm.area AREA
, vq.AWS, vq.AWS3, vq.PCS, vq.N77, vq.CBRS, vq.FDMIMO, vq.MMW, vq.LOAD_TIMESTAMP  FROM CARRIER_LOCATION_N5L cl LEFT JOIN DIR_COUNTY dc ON cl.Market = dc.Market AND cl.FIPS = dc.FIPS      JOIN DIR_MARKET dm ON cl.market = dm.market AND dc.MARKETSTR = dm.MARKETSTR
 LEFT JOIN VISION_QUALIFICATION vq ON  cl.nwfid = vq.FUZE_SITE_ID AND DATE_FORMAT(vq.SOURCE_DATE, '%m/%Y') = '09/2024'  LEFT JOIN SOLUTION_SITE_OFFLOAD_N5L_SNAPSHOT SS ON  SS.AGG_UNIQUEID = cl.AGG_UNIQUEID  AND SS.FUZESITEID = cl.NWFID  LEFT JOIN SOLUTION_N5L_SNAPSHOT S  ON S.SolutionID = SS.SolutionID   AND S.DELETED = 0 AND S.DISABLED = 0  AND S.OnAirYear IN (0,2025,2026,2027,2028,2029)  AND UPPER(S.STATUS) NOT IN ('CANCELLED','DELETED','REJECTED','REJECTED_PROPOSAL','CANCELED')  WHERE 1 = 1  AND cl.ONAIR = 1  AND S.PARENTSOLUTIONID IN (91912)  GROUP BY cl.Market, cl.AGG_UNIQUEID ) a LEFT JOIN VPI_DATA_N5L vpidt ON a.AGG_UNIQUEID = vpidt.agg_unique_id  AND vpidt.cptmonth = STR_TO_DATE('01/01/2025', '%m/%d/%Y')  AND vpidt.projecteddate = '2025'  WHERE 1=1   AND a.Vendor  IN ( 'SAM', 'NOK' )  LIMIT 10 OFFSET 0
